CREATE TABLE addressmig_green.dpa
(
    record_identifier INTEGER,
    change_type VARCHAR(1) ,
    pro_order BIGINT,
    uprn BIGINT NOT NULL,
    udprn BIGINT,
    organisation_name VARCHAR(60) ,
    department_name VARCHAR(60) ,
    sub_building_name VARCHAR(30) ,
    building_name VARCHAR(80) ,
    building_number INTEGER,
    dependent_thoroughfare VARCHAR(80) ,
    thoroughfare VARCHAR(80) ,
    double_dependent_locality VARCHAR(35) ,
    dependent_locality VARCHAR(35) ,
    post_town VARCHAR(30) ,
    postcode VARCHAR(8) ,
    postcode_type VARCHAR(1) ,
    delivery_point_suffix VARCHAR(2) ,
    welsh_dependent_thoroughfare VARCHAR(80) ,
    welsh_thoroughfare VARCHAR(80) ,
    welsh_double_dependent_locality VARCHAR(35) ,
    welsh_dependent_locality VARCHAR(35) ,
    welsh_post_town VARCHAR(30) ,
    po_box_number VARCHAR(6),
    process_date DATE,
    start_date DATE,
    end_date DATE,
    last_update_date DATE,
    entry_date DATE
    );